name: Build Image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Container Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/fkthfvk112/nuzelcat:latest

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          timeout: 600s
          script: |
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/fkthfvk112/nuzelcat:latest
            docker rm -f live-cat-server || true
            docker run -d \
              -p 8082:8080 \
              --name live-cat-server \
              -e DB_URL_CAT_LIVE=${{ secrets.DB_URL_CAT_LIVE }} \
              -e DB_USER_CAT_LIVE=${{ secrets.DB_USER_CAT_LIVE }} \
              -e DB_PW_CAT_LIVE=${{ secrets.DB_PW_CAT_LIVE }} \
              -e PROFILE_CAT=live \
              -e SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} \
              -e SMTP_SECRET=${{ secrets.SMTP_SECRET }} \
              -e CN_CLOUDNAME=${{ secrets.CN_CLOUDNAME }} \
              -e CN_API_KEY=${{ secrets.CN_API_KEY }} \
              -e CN_API_SECRET=${{ secrets.CN_API_SECRET }} \
              -e SERVER_ALLOWED_URL_CAT_CSV=${{ secrets.SERVER_ALLOWED_URL_CAT_CSV }} \
              -v /home/ubuntu/web/logs/cat/live/:${{ secrets.LOG_PATH }} \
              --network rdb_network \
                ghcr.io/fkthfvk112/nuzelcat:latest